[tool.poetry]
name = "django-modeltranslation"
version = "0.18.10"
description = "Translates Django models using a registration approach."
authors = ["Peter Eschler <peschler@gmail.com>"]
maintainers = ["Serhii Tereshchenko <serg.partizan@gmail.com>"]
packages = [
    { include = "modeltranslation" },
]

[tool.poetry.dependencies]
python = ">=3.8,<4"
django = ">=4.2"
ruff = "^0.0.292"

[tool.poetry.dev-dependencies]
pdbpp = "*"
parameterized = "*"
pytest-cov = "*"
pytest = "*"
pytest-sugar = "*"
pytest-django = "*"
django-types = "*"

[tool.ruff]
line-length = 100
target-version = "py38"
ignore = [
    "E501",   # line length is handled by formatter
]
