[tool.poetry]
name = "django-modeltranslation"
version = "0.19.0"
description = "Translates Django models using a registration approach."
authors = ["Peter Eschler <peschler@gmail.com>"]
maintainers = ["Serhii Tereshchenko <serg.partizan@gmail.com>"]
packages = [
    { include = "modeltranslation" },
]

[tool.poetry.dependencies]
python = ">=3.8,<4"
django = ">=4.2"
typing-extensions = {version = ">=4.0.1", python = "<3.11"}

[tool.poetry.group.dev.dependencies]
ruff = "*"
pdbpp = "*"
parameterized = "*"
pytest-cov = "*"
pytest = "*"
pytest-sugar = "*"
pytest-django = "*"
django-stubs = "*"
mypy = "*"
build = "*"

[tool.ruff]
line-length = 100
target-version = "py38"
[tool.ruff.lint]
ignore = [
    "E501",   # line length is handled by formatter
]

[tool.mypy]
python_version = "3.8"
incremental = true
warn_unused_ignores = true
warn_redundant_casts = true
warn_unused_configs = true
pretty = true
show_error_context = true
exclude = [
    'tests/'
]
disable_error_code = ["method-assign"]

[[tool.mypy.overrides]]
module  = ["modeltranslation.fields"]
disable_error_code = ["attr-defined", "has-type", "misc"]

[[tool.mypy.overrides]]
module  = ["modeltranslation.admin"]
disable_error_code = ["override", "attr-defined"]

[[tool.mypy.overrides]]
module  = ["modeltranslation.translator"]
disable_error_code = ["override", "attr-defined"]

[[tool.mypy.overrides]]
module = ["modeltranslation.manager"]
disable_error_code = ["override", "attr-defined", "return-value", "misc"]
