[tool.poetry]
name = "django-modeltranslation"
version = "0.16.1"
description = "Translates Django models using a registration approach."
authors = ["Peter Eschler <peschler@gmail.com>"]
maintainers = ["Serhii Tereshchenko <serg.partizan@gmail.com>"]
packages = [
    { include = "modeltranslation" },
]

[tool.poetry.dependencies]
python = ">=3.7,<4"
django = ">=3.2"
typing-extensions = "^4.4.0"

[tool.poetry.dev-dependencies]
pdbpp = "^0.10.2"
flake8 = "^3.7.9"
black = "^21.9b0"
pytest-cov = "^3.0.0"
pytest = "^7.1.2"
pytest-sugar = "^0.9.5"
pytest-django = "^4.5.2"
django-types = "^0.15.0"

[tool.black]
line-length = 100
skip-string-normalization = true

[tool.isort]
line_length = 100
multi_line_output = 3
skip_gitignore = true
include_trailing_comma = true
