# Generated by Django 4.2.10 on 2024-04-20 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tests", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="manytomanyfieldmodel",
            name="self_call_1",
            field=models.ManyToManyField(to="tests.manytomanyfieldmodel"),
        ),
        migrations.AlterField(
            model_name="manytomanyfieldmodel",
            name="self_call_1_de",
            field=models.ManyToManyField(null=True, to="tests.manytomanyfieldmodel"),
        ),
        migrations.AlterField(
            model_name="manytomanyfieldmodel",
            name="self_call_1_en",
            field=models.ManyToManyField(null=True, to="tests.manytomanyfieldmodel"),
        ),
        migrations.AlterField(
            model_name="manytomanyfieldmodel",
            name="self_call_2",
            field=models.ManyToManyField(to="tests.manytomanyfieldmodel"),
        ),
        migrations.AlterField(
            model_name="manytomanyfieldmodel",
            name="self_call_2_de",
            field=models.ManyToManyField(null=True, to="tests.manytomanyfieldmodel"),
        ),
        migrations.AlterField(
            model_name="manytomanyfieldmodel",
            name="self_call_2_en",
            field=models.ManyToManyField(null=True, to="tests.manytomanyfieldmodel"),
        ),
        migrations.CreateModel(
            name="SecondSetNullForeignKeyModel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "test",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_set",
                        to="tests.testmodel",
                    ),
                ),
                (
                    "test_de",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_set",
                        to="tests.testmodel",
                    ),
                ),
                (
                    "test_en",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_set",
                        to="tests.testmodel",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="FirstSetNullForeignKeyModel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "test",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_set",
                        to="tests.testmodel",
                    ),
                ),
                (
                    "test_de",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_set",
                        to="tests.testmodel",
                    ),
                ),
                (
                    "test_en",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_set",
                        to="tests.testmodel",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
