# Generated by Django 4.2.10 on 2024-04-21 06:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tests", "0002_alter_manytomanyfieldmodel_self_call_1_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="firstsetnullforeignkeymodel",
            name="translated",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="firstsetnullforeignkeymodel",
            name="translated_de",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AddField(
            model_name="firstsetnullforeignkeymodel",
            name="translated_en",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AddField(
            model_name="secondsetnullforeignkeymodel",
            name="translated22",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="secondsetnullforeignkeymodel",
            name="translated22_de",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AddField(
            model_name="secondsetnullforeignkeymodel",
            name="translated22_en",
            field=models.TextField(blank=True, default="", null=True),
        ),
    ]
