name: Tests and PyPI publishing

on:
  push:
    branches:
      - main
    tags:
      - "*"
  pull_request:
  workflow_dispatch:

jobs:
  tests:
    name: Run tests Python ${{ matrix.python }}, Django ${{ matrix.django }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ["3.8", "3.9", "3.10", "3.11"]
        django: ["3.2", "4.1", "4.2"]
        exclude:
          - python: "3.11"
            django: "3.2"

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}

      - name: Install dependencies
        run: pip install tox tox-gh-actions

      - name: Run tests
        run: tox
        env:
          PYTHON_VERSION: ${{ matrix.python }}
          DJANGO: ${{ matrix.django }}

      - name: Publish coverage report
        uses: codecov/codecov-action@v3

  publish:
    name: Publish package to PyPI
    runs-on: ubuntu-latest
    needs:
      - tests

    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Build sdist and wheel
        run: |
          pip install pip setuptools wheel --upgrade
          python setup.py sdist bdist_wheel
      - name: Publish a Python distribution to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_TOKEN }}
          