name: Linting and code quality

on:
  push:
    branches:
      - main
    tags:
    paths:
      - '**.py'
      - .github/workflows/code_quality.yml
  pull_request:
    paths:
      - '**.py'
      - .github/workflows/code_quality.yml
  workflow_dispatch:

jobs:
  linting:
    name: Code-quality checks
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toxenv:
          - isort
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: pip install tox
      - run: tox
        env:
          TOXENV: ${{ matrix.toxenv }}
          